{{ config(materialized='view')}}
with TAB_DESPESAS_AGRUPAMENTO_REL as 
{
    SELECT * FROM QA_RDS_DWQA.TAB_DESPESAS_AGRUPAMENTO_REL

}
SELECT
    _AIRBYTE_RAW_ID,
    _AIRBYTE_EXTRACTED_AT,
    _AIRBYTE_META,
    CD_CODIGO,
    CD_DESPESA,
    CD_TIPO_DESPESA
FROM
    TAB_DESPESAS_AGRUPAMENTO_REL;

