{{ config(materialized='view')}}
with TAB_LI_FOLLOW as 
{
    SELECT * FROM QA_RDS_DWQA.TAB_LI_FOLLOW

}

SELECT
    DT_LI,
    TX_NLI,
    CD_TIPO,
    CK_ROBO,
    DT_DIDA,
    TX_DIDA,
    TX_NREF,
    TX_SREF,
    CD_FIORDE,
    CK_LI_SUB,
    CK_STATUS,
    DT_CHEGADA,
    DT_CRIACAO,
    DT_REMOCAO,
    TX_NREF_LI,
    TX_PRODUTO,
    CK_NUM_ROBO,
    DT_EMBARQUE,
    TX_INCOTERM,
    CD_FATURISTA,
    DT_ALTERACAO,
    CD_EXPORTADOR,
    CD_IMPORTADOR,
    CD_RESP_LISUB,
    CD_VIA_TRANSP,
    CK_EXTRATO_LI,
    CD_DESPACHANTE,
    CD_TIPO_EVENTO,
    DT_DESEMBARACO,
    DT_FATURAMENTO,
    DT_SOLICITACAO,
    CD_LOCAL_DESEMB,
    CD_MOTIVO_LISUB,
    CD_URF_DESPACHO,
    DT_CANCELAMENTO,
    DT_PREV_CHEGADA,
    TX_COMPLEMENTAR,
    CD_TIPO_PROCESSO,
    DT_PREV_EMBARQUE,
    TX_NREF_EMBARQUE,
    CD_ANALISTA_FIORDE,
    CD_STATUS_PROCESSO,
    DT_LIB_FATURAMENTO,
    TX_NLI_SUBSTITUIDA,
    CD_USUARIO_INCLUSAO,
    CD_USUARIO_ALTERACAO,
    DT_ULT_CONS_ROBOLIWEB,
    TX_MSG_CONS_ROBOLIWEB,
    DT_REABERTURA_PROCESSO,
    DT_SOLIC_CANC_SISCOMEX,
    CD_USUARIO_CANCELAMENTO,
    DT_RETORNO_CANC_SISCOMEX,
    TX_RETORNO_CANC_SISCOMEX,
    CD_DESPACHANTE_VERIFICA_LI,
    CD_USU_SOLIC_CANC_SISCOMEX
FROM
    TAB_LI_FOLLOW;





